// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4tCiVxCKoqPmtQ-ZoYBW5-ev33aCFgQ0',
    appId: '1:394500715189:web:e5b26d08115a4db8c9c4fc',
    messagingSenderId: '394500715189',
    projectId: 'onlineshop-1671a',
    authDomain: 'onlineshop-1671a.firebaseapp.com',
    storageBucket: 'onlineshop-1671a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB909Oe-pNQZvfiDOYZ48LEhedeT1jIG10',
    appId: '1:394500715189:android:8480bbb85d4b5290c9c4fc',
    messagingSenderId: '394500715189',
    projectId: 'onlineshop-1671a',
    storageBucket: 'onlineshop-1671a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3hGvUxdRFjkCnSxqUbAAD6pQSAAh0iZg',
    appId: '1:394500715189:ios:fed1337375bd5152c9c4fc',
    messagingSenderId: '394500715189',
    projectId: 'onlineshop-1671a',
    storageBucket: 'onlineshop-1671a.appspot.com',
    iosClientId: '394500715189-6avtv0jq2e79p5irqrp1nofhfdcp703b.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3hGvUxdRFjkCnSxqUbAAD6pQSAAh0iZg',
    appId: '1:394500715189:ios:2e0e8fe0ccc567d2c9c4fc',
    messagingSenderId: '394500715189',
    projectId: 'onlineshop-1671a',
    storageBucket: 'onlineshop-1671a.appspot.com',
    iosClientId: '394500715189-5j1iq5i1vdstudms6tucaqagob8pmand.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineShop.RunnerTests',
  );
}
